{
  "failures": [
    {
      "message":
        "Danger failed to run `/Users/orta/dev/projects/danger/danger-js/source/runner/_tests/fixtures/__DangerfileThrows.js`."
    }
  ],
  "warnings": [],
  "messages": [],
  "markdowns": [
    "## Error Error\n```\nfailure\nError: failure\n    at Object.<anonymous> (/Users/orta/dev/projects/danger/danger-js/source/runner/_tests/fixtures/__DangerfileThrows.js:3:7)\n    at Module._compile (module.js:624:30)\n    at requireFromString (/Users/orta/dev/projects/danger/danger-js/node_modules/require-from-string/index.js:28:4)\n    at Object.<anonymous> (/Users/orta/dev/projects/danger/danger-js/distribution/runner/runners/inline.js:95:21)\n    at step (/Users/orta/dev/projects/danger/danger-js/distribution/runner/runners/inline.js:32:23)\n    at Object.next (/Users/orta/dev/projects/danger/danger-js/distribution/runner/runners/inline.js:13:53)\n    at /Users/orta/dev/projects/danger/danger-js/distribution/runner/runners/inline.js:7:71\n    at new Promise (<anonymous>)\n    at __awaiter (/Users/orta/dev/projects/danger/danger-js/distribution/runner/runners/inline.js:3:12)\n    at Object.runDangerfileEnvironment (/Users/orta/dev/projects/danger/danger-js/distribution/runner/runners/inline.js:66:12)\n```\n### Dangerfile\n```\n1| throw new Error(\"failure\")\n2| \n--------^\n```\n  "
  ]
}
